// Цвета использованные в графике
export const customTheme = {
  axisBorder: "Transparent",
  axisTitleColor: "white",
  annotationsGripsBackroundBrush: "white",
  annotationsGripsBorderBrush: "white",
  axis3DBandsFill: "Transparent",
  axisBandsFill: "Transparent",
  axisPlaneBackgroundFill: "Transparent",
  columnFillBrush: "white",
  columnLineColor: "white",
  cursorLineBrush: "#ffffff",
  defaultColorMapBrush: [
      { offset: 0, color: "#ffffff" },
      { offset: 0.5, color: "#ffffff" },
      { offset: 1, color: "#ffffff" }
  ],
  downBandSeriesFillColor: "#52CC5490",
  downBandSeriesLineColor: "#E26565FF",
  downBodyBrush: "white",
  downWickColor: "white",
  gridBackgroundBrush: "white",
  gridBorderBrush: "white",
  labelBackgroundBrush: "#ffffff",
  labelBorderBrush: "#6495ED",
  labelForegroundBrush: "#EEEEEE",
  legendBackgroundBrush: "#1D2C35",
  lineSeriesColor: "white",
  loadingAnimationBackground: "#333",
  loadingAnimationForeground: "#fff",
  majorGridLineBrush: "#ffffff22",
  minorGridLineBrush: "#ffffff11",
  mountainAreaBrush: "white",
  mountainLineColor: "white",
  overviewFillBrush: "white",
  planeBorderColor: "white",
  rolloverLineBrush: "#FD9F2533",
  rubberBandFillBrush: "#99999933",
  rubberBandStrokeBrush: "#99999977",
  sciChartBackground: "Transparent",
  scrollbarBackgroundBrush: "white",
  scrollbarBorderBrush: "white",
  scrollbarGripsBackgroundBrush: "white",
  scrollbarViewportBackgroundBrush: "white",
  scrollbarViewportBorderBrush: "white",
  shadowEffectColor: "white",
  textAnnotationBackground: "white",
  textAnnotationForeground: "#EEEEEE",
  tickTextBrush: "white",
  upBandSeriesFillColor: "white",
  upBandSeriesLineColor: "white",
  upBodyBrush: "#ffffffA0",
  upWickColor: "white"
}